listen: 0.0.0.0
port: 8081
static: ../static
configjs: ../static/config.js
dealpics: ../../dealpics
dealvideos: ../../dealvideos
sourcepics: ../../sourcepics
sourcevideos: ../../sourcevideos
password: viewer
dbfile: ./file.db